

[deploy]
startCommand = ""
restartPolicyType = "ON_FAILURE"

[[services]]
name = "backend-gh"
root = "backend"
dockerfilePath = "Dockerfile"
builder = "DOCKERFILE"

[[services]]
name = "frontend-gh"
root = "frontend"
dockerfilePath = "Dockerfile"
builder = "DOCKERFILE"
